################################################################################
################# West Coast Env Health GLMM Analysis ##########################
#################      Step 2: Covariates        ###############################
################################################################################

### code adapted from T. Gallo ###
### NDVI composite dataset generated by G. Cova ##

## packages 
library(raster)
library(sf)
library(dplyr)
library(mapview)
library(rgdal)
library(raster)
library(here)

# load all sites
all_sites <- read.csv("coyote_occu_TAWA.csv", stringsAsFactors = FALSE)

# check site list 
unique(all_sites$Name)

# turn coordinates into spatial points

all_sites$zone <- c(rep("10N", 41))
points <- st_as_sf(all_sites, coords = c("UTM_East", "UTM_North"), crs = 
                     "+proj=utm +zone=10 +datum=WGS84")
st_crs(points)
# order data by Location Name 
points <- points[order(points$Name),]
nrow(points)

# check to make sure they are where they are supposed to be
mapview(points)